pipeline {
    agent any

    stages {
        stage('Unit tests - Backend') {
            steps {
                dir ('buntracker-backend') {
                    go test -v ./...
                }
                sh 'date'
            }
        }
    }
}
