pipeline {
    agent any

    tools {
        // This must match the name you gave the tool in Step 1
        go 'go-1.25.6'
    }

    stages {
        stage('Unit tests - Backend') {
            steps {
                dir('bugtracker-backend') {
                    // This will now work because 'go' is in the PATH
                    sh 'go test -v ./...'
                }
                sh 'date'
            }
        }
    }
}