pipeline {
    agent any

    // tools {
        // This must match the name you gave the tool in Step 1
    //     go 'go-1.25.6'
    // }

    stages {
//         stage('Prepare Environment') {
//             steps {
//                 // Create the directory and set permissions before the Docker agent starts
//                 sh 'mkdir -p /var/jenkins_home/go-cache && chmod 777 /var/jenkins_home/go-cache'
//                 }
//        }
        stage('Unit tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    // Redirect GOCACHE and GOPATH to the workspace
                    // This ensures downloads persist between runs
                    args '''
                        -e GOCACHE=${WORKSPACE}/.go-cache/cache
                        -e GOPATH=${WORKSPACE}/.go-cache/path 
                        -v /var/jenkins_home/go-cache:/var/jenkins_home/go-cache
                    '''
                }
            }
            steps {
                dir('bugtracker-backend') {
                    // This will now work because 'go' is in the PATH
                    sh 'go test -v ./...'
                }
                sh 'date'
            }
        }
        stage('Unit tests - Frontend'){
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                    // Redirect npm cache to the workspace to avoid permission issues
                    args '-e npm_config_cache=${WORKSPACE}/.npm-cache'
                    // This ensures downloads persist between runs
                    // args '-v /var/jenkins_home/npm-cache:/.npm -e npm_config_cache=/.npm'
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                      # Forcefully remove node_modules if it exists
                      # This bypasses the npm 'rmdir' struggle
                      rm -rf node_modules
                      npm ci
                      npm test
                    '''
                }
            }
        }
    }
}